=== Khmelov/JD2018-04-11/src/by/it/dkruchek/jd02_09/Schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
targetNamespace="http://jd02_09.dkruchek.it.by"
xmlns:tns="http://jd02_09.dkruchek.it.by"
elementFormDefault="qualified">
    <element name="Persons">
        <complexType>
            <sequence>
                <element name="Person"
                         type="tns:Person"
                         maxOccurs="unbounded">
                </element>
            </sequence>
        </complexType>
    </element>
    <complexType name="Person">
        <sequence>
            <element name="Login" type="string"/>
            <element name="Password" type="string"/>
            <element name="Email" type="string"/>
            <element name="Ads" type="tns:Ads"/>
        </sequence>
    </complexType>
    <complexType name="Ads">
        <sequence>
            <element name="Ad"
                     type="tns:Ad"
                     maxOccurs="unbounded"/>
        </sequence>
    </complexType>
    <complexType name="Ad">
        <sequence>
            <element name="Description" type="string"/>
            <element name="Address" type="string"/>
            <element name="Price" type="tns:Price"/>
            <element name="Area" type="double"/>
            <element name="Floor" type="positiveInteger"/>
            <element name="Floors" type="positiveInteger"/>
            <element name="Rooms" type="positiveInteger"/>
        </sequence>
    </complexType>
    <complexType name="Price">
        <simpleContent>
            <extension base="double">
                <attribute name="currency"
                            type="string"
                            use="required">
                </attribute>
            </extension>
        </simpleContent>
    </complexType>
</schema>

=== Khmelov/JD2018-04-11/src/by/it/shekh/jd02_09/Persons+xsd.xml
<?xml version="1.0" encoding="UTF-8" ?>
<Persons xmlns="http://jd02_09.shekh.it.by"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://jd02_09.shekh.it.by Schema.xsd"
>
    <Person>
        <Login>Stanis</Login>
        <Password>Qwerty12345</Password>
        <Email>sts.shekh@gmail.com</Email>
        <Ads>
            <Ad>
                <Description>
                    Шикарная квартира в самом центре за дорого!
                </Description>
                <Address>
                    ул. Ленина д.1 кв.13
                </Address>
                <Price currency="$$$$">123456.0</Price>
                <Area>55.5</Area>
                <Floor>3</Floor>
                <Floors>5</Floors>
                <Rooms>2</Rooms>
            </Ad>
            <Ad>
                <Description>
                    Нешикарная квартира не в центре за дешево.
                </Description>
                <Address>
                    ул. Космическая д.3 кв.16
                </Address>
                <Price currency="EU">44444.0</Price>
                <Area>44.4</Area>
                <Floor>4</Floor>
                <Floors>4</Floors>
                <Rooms>2</Rooms>
            </Ad>
        </Ads>
    </Person>
    <Person>
        <Login>Fedya</Login>
        <Password>asdfg12345</Password>
        <Email>fedya12345@mail.ru</Email>
        <Ads>
            <Ad>
                <Description>
                    Однокомнатная квартира!
                </Description>
                <Address>
                    ул. Ленина д.1 кв.1.
                </Address>
                <Price currency="BYN">999999.0</Price>
                <Area>55.5</Area>
                <Floor>1</Floor>
                <Floors>5</Floors>
                <Rooms>1</Rooms>
            </Ad>
        </Ads>
    </Person>
</Persons>

=== Khmelov/JD2018-04-11/src/by/it/gavrilchik/jd02_09/Persons+xsd.xml
<?xml version="1.0" encoding="UTF-8"?>
<Persons xmlns="http://jd02_09.gavrilchik.it.by"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://jd02_09.gavrilchik.it.by Schema.xsd"
>
    <Person>
        <Login>Vasya</Login>
        <Password>qwerty12345</Password>
        <Email>vasya12345@mail.ru</Email>
        <Ads>
              <Ad>
                  <Description>
                      Superior flat in the center expensive!
                  </Description>
                  <Address>
                      13-1, Lenina ave.
                  </Address>
                  <Price currency="EU">123456.0</Price>
                  <Area>55.5</Area>
                  <Floor>3</Floor>
                  <Floors>5</Floors>
                  <Rooms>2</Rooms>
              </Ad>
            <Ad>
            <Description>
                Economy flat in the center cheap!
            </Description>
            <Address>
                16-3, Kosmicheskaya str.
            </Address>
            <Price currency="USD">44444.0</Price>
            <Area>44.4</Area>
            <Floor>4</Floor>
            <Floors>4</Floors>
                <Rooms>3</Rooms>
        </Ad>
        </Ads>
    </Person>
    <Person>
        <Login>Fedya</Login>
        <Password>asdfg12345</Password>
        <Email>fedya12345@mail.ru</Email>
        <Ads>
            <Ad>
                <Description>
                    One room flat!
                </Description>
                <Address>
                    1-1, Lenina ave.
                </Address>
                <Price currency="BYN">999999.0</Price>
                <Area>55.5</Area>
                <Floor>1</Floor>
                <Floors>5</Floors>
                <Rooms>1</Rooms>
            </Ad>

        </Ads>
    </Person>
</Persons>
