=== Khmelov/JD2018-04-11/src/by/it/kasiyanov/jd02_07/classWork/Schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://it.by/kasiyanov/xmlschema"
        xmlns:tns="http://it.by/kasiyanov/xmlschema"
        elementFormDefault="qualified">
<element name="Persons">
    <complexType>
        <sequence>
        <element name="Person"
                 type="tns:Person"
                 minOccurs="1"
                 maxOccurs="unbounded">
        </element>
    </sequence>

    </complexType>
</element>
    <complexType name="Person">
        <sequence>
            <element name="Login" type="string"/>
            <element name="Password" type="string"/>
            <element name="Email" type="string"/>
            <element name="Ads" type="tns:Ads"/>
        </sequence>
    </complexType>

    <complexType name="Ads">
        <sequence>
            <element name="Ad"
                     type="tns:Ad"
                     minOccurs="1"
                     maxOccurs="unbounded"></element>
        </sequence>
    </complexType>

    <complexType name="Ad">
        <sequence>
            <element name="Description" type="string"/>
            <element name="Adress" type="string"/>
            <element name="Price" type="tns:Price"/>
            <element name="Area" type="double"/>
            <element name="Floor" type="integer"/>
            <element name="Floors" type="integer"/>
            <element name="Rooms" type="integer"/>
        </sequence>
    </complexType>

    <complexType name="Price">
        <simpleContent>
            <extension base="double">
                <attribute
                    name="currency"
                    type="string"
                    use="required"/>
            </extension>

        </simpleContent>
    </complexType>

</schema>

=== Khmelov/JD2018-04-11/src/by/it/kasiyanov/jd02_07/classWork/Pesons+XSD.xml
<?xml version="1.0" encoding="UTF-8"?>
<Persons xmlns="http://it.by/kasiyanov/xmlschema"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://it.by/kasiyanov/xmlschema Schema.xsd"
>
    <Person>
        <Login>Vasya</Login>
        <Password>qwerty12345</Password>
        <Email>vasya12345@mail.ru</Email>
        <Ads>
            <Ad>
                <Description>
                    Шикарная квартира в центре за дорого!
                </Description>
                <Adress>
                    ул.Ленина д.1 кв.13
                </Adress>
                <Price currency="BYN">123456.0</Price>
                <Area>55.55</Area>
                <Floor>3</Floor>
                <Floors>5</Floors>
                <Rooms>2</Rooms>
            </Ad>
            <Ad>
                <Description>
                    Не шикарная квартира не в центре за дёшево!
                </Description>
                <Adress>
                    ул.Космическая д.3 кв.16
                </Adress>
                <Price currency="BYN">4444.0</Price>
                <Area>44.44</Area>
                <Floor>4</Floor>
                <Floors>4</Floors>
                <Rooms>2</Rooms>
            </Ad>
        </Ads>
    </Person>
    <Person>
        <Login>Fedya</Login>
        <Password>asdfg12345</Password>
        <Email>fedya12345@mail.ru</Email>
        <Ads>
            <Ad>
                <Description>
                    Однокомнатная квартира!
                </Description>
                <Adress>
                    ул.Ленина д.1 кв.1
                </Adress>
                <Price currency="BYN">9999.0</Price>
                <Area>99.99</Area>
                <Floor>1</Floor>
                <Floors>1</Floors>
                <Rooms>1</Rooms>
            </Ad>
        </Ads>
    </Person>
</Persons>
