=== Khmelov/JD2018-04-11/src/by/it/zaleschonok/jd02_07/Schema.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://it.by/zaliashchonak/xmlschema"
        xmlns:tns="http://it.by/zaliashchonak/xmlschema"
        elementFormDefault="qualified">
    <element name="Clients">
        <complexType>
            <sequence>
                <element name="Client"
                         type="tns:Client"
                         maxOccurs="unbounded">
                </element>
            </sequence>
        </complexType>
    </element>
    <complexType name="Client">
        <sequence>
            <element name="Nickname" type="string"/>
            <element name="Password" type="string"/>
            <element name="Email" type="string"/>
            <element name="Ads" type="tns:Ads"/>
        </sequence>
    </complexType>
    <complexType name="Ads">
        <sequence>
            <element name="Ad"
                     type="tns:Ad"
                     maxOccurs="unbounded"/>
        </sequence>
    </complexType>
    <complexType name="Ad">
        <sequence>
            <element name="Product" type="string"/>
            <element name="Price" type="tns:Price"/>
            <element name="Description" type="string"/>
        </sequence>
    </complexType>
    <complexType name="Price">
        <simpleContent>
            <extension base="double">
                <attribute
                        name="currency"
                        type="string"
                        use="required"/>
            </extension>
        </simpleContent>
    </complexType>
</schema>

=== Khmelov/JD2018-04-11/src/by/it/zaleschonok/jd02_07/Clients+xsd.xml
<?xml version="1.0" encoding="UTF-8" ?>
<Clients xmlns="http://it.by/zaliashchonak/xmlschema"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://it.by/zaliashchonak/xmlschema Schema.xsd">
    <Client>
        <Nickname>Вася1</Nickname>
        <Password>Пароль1</Password>
        <Email>mail1@gmail.com</Email>
        <Ads>
            <Ad>
                <Product>Product1</Product>
                <Price currency="BYN">1000</Price>
                <Description>Product1 Description</Description>
            </Ad>
            <Ad>
                <Product>Product2</Product>
                <Price currency="BYN">2000</Price>
                <Description>Product2 Description</Description>
            </Ad>
        </Ads>
    </Client>
    <Client>
        <Nickname>Вася2</Nickname>
        <Password>Пароль2</Password>
        <Email>mail2@gmail.com</Email>
        <Ads>
            <Ad>
                <Product>Product3</Product>
                <Price currency="BYN">3000</Price>
                <Description>Product3 Description</Description>
            </Ad>
        </Ads>
    </Client>
</Clients>

=== Khmelov/JD2018-04-11/src/by/it/zaleschonok/jd02_09/Clients+xsd.xml
<?xml version="1.0" encoding="UTF-8" ?>
<Clients xmlns="http://jd02_09.zaleschonok.it.by"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://jd02_09.zaliashchonak.it.by Schema.xsd">
    <Client>
        <Nickname>Вася1</Nickname>
        <Password>Пароль1</Password>
        <Email>mail1@gmail.com</Email>
        <Ads>
            <Ad>
                <Product>Product1</Product>
                <Price currency="BYN">1000</Price>
                <Description>Product1 Description</Description>
            </Ad>
            <Ad>
                <Product>Product2</Product>
                <Price currency="BYN">2000</Price>
                <Description>Product2 Description</Description>
            </Ad>
        </Ads>
    </Client>
    <Client>
        <Nickname>Вася2</Nickname>
        <Password>Пароль2</Password>
        <Email>mail2@gmail.com</Email>
        <Ads>
            <Ad>
                <Product>Product3</Product>
                <Price currency="BYN">3000</Price>
                <Description>Product3 Description</Description>
            </Ad>
        </Ads>
    </Client>
</Clients>
