=== Khmelov/JD2018-04-11/src/by/it/mokhart/jd02_09/Schema.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://jd02_09.mokhart.it.by"
        xmlns:tns="http://jd02_09.mokhart.it.by"
        elementFormDefault="qualified">
    <element name="Clients">
        <complexType>
            <sequence>
                <element name="Client"
                         type="tns:Client"
                         maxOccurs="unbounded">
                </element>
            </sequence>
        </complexType>
    </element>

    <complexType name="Client">
        <sequence>
            <element name="Login" type="string"/>
            <element name="Password" type="string"/>
            <element name="Email" type="string"/>
            <element name="Clothes" type="tns:Clothes"/>
        </sequence>
    </complexType>

    <complexType name="Clothes">
        <sequence>
            <element name="Cloth"
                     type="tns:Cloth"
                     maxOccurs="unbounded"
            />
        </sequence>
    </complexType>

    <complexType name="Cloth">
        <sequence>
            <element name="Description" type="string"/>
            <element name="Price" type="tns:Price"/>
        </sequence>
    </complexType>

    <complexType name="Price">
        <simpleContent>
            <extension base="double">
                <attribute
                        name="currency"
                        type="string"
                        use="required"/>
            </extension>
        </simpleContent>
    </complexType>

</schema>

=== Khmelov/JD2018-04-11/src/by/it/mokhart/jd02_09/Clients+xsd.xml
<?xml version="1.0" encoding="UTF-8" ?>
<Clients xmlns="http://jd02_09.mokhart.it.by"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://jd02_09.mokhart.it.by Schema.xsd">
    <Client>
        <Login>Kate</Login>
        <Password>0000</Password>
        <Email>kate.d@mail.ru</Email>
        <Clothes>
            <Cloth>
                <Description>
                    Хорошая одежда, всё круто!
                </Description>
                <Price currency="RU">167</Price>
            </Cloth>
            <Cloth>
                <Description>
                    Качество очень хорошее, всем советую!
                </Description>
                <Price currency="EUR">79</Price>
            </Cloth>
        </Clothes>
    </Client>
    <Client>
        <Login>Anton</Login>
        <Password>antonio</Password>
        <Email>an@mail.ru</Email>
        <Clothes>
            <Cloth>
                <Description>
                    Очень классные вещи, советую!
                </Description>
                <Price currency="USD">193</Price>
            </Cloth>
            <Cloth>
                <Description>
                    Не лучшее качество, цена не соответсвует...
                </Description>
                <Price currency="BYN">118</Price>
            </Cloth>
        </Clothes>
    </Client>
</Clients>
