=== Khmelov/JD2018-04-11/src/by/it/krivenkova/jd02_07/Schema.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://jd02_09.krivenkova.it.by"
        xmlns:tns="http://jd02_09.krivenkova.it.by"
        elementFormDefault="qualified">
    <element name="Users">
        <complexType>
            <sequence>
                <element name="User"
                         type="tns:User"
                         maxOccurs="unbounded">
                </element>
            </sequence>
        </complexType>
    </element>
    <complexType name="User">
        <sequence>
            <element name="Login" type="string"/>
            <element name="Password" type="string"/>
            <element name="Surname" type="string"/>
            <element name="Name" type="string"/>
            <element name="Patronymic" type="string"/>
            <element name="Email" type="string"/>
            <element name="Routes" type="tns:Routes"/>
        </sequence>
    </complexType>
    <complexType name="Routes">
        <sequence>
            <element name="Route"
                     type="tns:Route"
                     maxOccurs="unbounded"
            />
        </sequence>
    </complexType>
    <complexType name="Route">
        <sequence>
            <element name="DepTown" type="string"/>
            <element name="DepDate" type="string"/>
            <element name="DepTime" type="string"/>
            <element name="ArrTown" type="string"/>
            <element name="Price" type="tns:Price"/>
            <element name="NumTickets" type="integer"/>
        </sequence>
    </complexType>
    <complexType name="Price">
        <simpleContent>
            <extension base="double">
                <attribute
                        name="currency"
                        type="string"
                        use="required"/>
            </extension>
        </simpleContent>
    </complexType>
    <complexType name="Date">
        <simpleContent>
            <extension base="date">
                <attribute
                        name="usDate"
                        type="string"
                        use="required"/>
            </extension>
        </simpleContent>
    </complexType>
    <complexType name="Time">
        <simpleContent>
            <extension base="time">
                <attribute
                        name="usTime"
                        type="string"
                        use="required"/>
            </extension>
        </simpleContent>
    </complexType>
</schema>

=== Khmelov/JD2018-04-11/src/by/it/krivenkova/jd02_07/Users+xsd.xml
<?xml version="1.0" encoding="UTF-8" ?>
<Users xmlns="http://jd02_09.krivenkova.it.by"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="http://jd02_09.krivenkova.it.by} Schema.xsd">
        <User>
            <Login>Kira</Login>
            <Password>moon</Password>
            <Surname>Афонко</Surname>
            <Name>Кирилл</Name>
            <Patronymic>Васильевич</Patronymic>
            <Email>kirAf@mail.ru</Email>
            <Routes>
                <Route>
                    <DepTown>Минск</DepTown>
                    <DepDate>12.08.2016</DepDate>
                    <DepTime>18:30</DepTime>
                    <ArrTown>Москва</ArrTown>
                    <Price currency="$$$$">15.2</Price>
                    <NumTickets>2</NumTickets>
                </Route>
                <Route>
                    <DepTown>Таллин</DepTown>
                    <DepDate >24.05.2017</DepDate>
                    <DepTime>06:30</DepTime>
                    <ArrTown>Берлин</ArrTown>
                    <Price currency="$$$$">72.6</Price>
                    <NumTickets>1</NumTickets>
                </Route>
            </Routes>
        </User>
        <User>
            <Login>lemon</Login>
            <Password>tark</Password>
            <Surname>Самохин</Surname>
            <Name>Максим</Name>
            <Patronymic>Николаевич</Patronymic>
            <Email>Samoh@mail.ru</Email>
            <Routes>
                <Route>
                    <DepTown>Белосток</DepTown>
                    <DepDate>08.04.2017</DepDate>
                    <DepTime>12:15</DepTime>
                    <ArrTown>Львов</ArrTown>
                    <Price currency="$$$$">50.3</Price>
                    <NumTickets>1</NumTickets>
                </Route>
            </Routes>
        </User>
    </Users>
