=== Khmelov/JD2018-04-11/src/by/it/kasiyanov/jd02_09/Schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://jd02_09.kasiyanov.it.by"
        xmlns:tns="http://jd02_09.kasiyanov.it.by"
        elementFormDefault="qualified">
    <element name="TravelAgents">
        <complexType>
            <sequence>
                <element name="TravelAgent"
                         type="tns:TravelAgent"
                         minOccurs="1"
                         maxOccurs="unbounded">
                </element>
            </sequence>

        </complexType>
    </element>
    <complexType name="TravelAgent">
        <sequence>
            <element name="Name" type="string"/>
            <element name="Login" type="string"/>
            <element name="Pasword" type="string"/>
            <element name="Email" type="string"/>
            <element name="TravelOffers" type="tns:TravelOffers"/>
        </sequence>
    </complexType>

    <complexType name="TravelOffers">
        <choice>
            <element name="TravelOffer"
                     type="tns:TravelOffer"
                     minOccurs="1"
                     maxOccurs="unbounded"></element>
        </choice>
    </complexType>

    <complexType name="TravelOffer">
        <sequence>
            <element name="Description" type="string"/>
            <element name="TypeOfTrevel" type="string"/>
            <element name="Destination" type="string"/>
            <element name="Hotel" type="string"/>
            <element name="LevelOfAccommodation" type="string"/>
            <element name="NumberOfNight" type="integer"/>
            <element name="Price" type="double"/>
        </sequence>
    </complexType>
</schema>

=== Khmelov/JD2018-04-11/src/by/it/kasiyanov/jd02_09/TravelAgents+XSD.xml
<?xml version="1.0" encoding="UTF-8"?>
<TravelAgents xmlns="http://jd02_09.kasiyanov.it.by"
			  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
			  xsi:schemaLocation="http://jd02_09.kasiyanov.it.by Schema.xsd"
>

	<TravelAgent>
		<Name>Alina</Name>
		<Login>Alina</Login>
		<Pasword>qwerty</Pasword>
		<Email>Alina@gmail.com</Email>
		<TravelOffers>
			<TravelOffer>
				<Description>
					Великолепные песчаные пляжи...
				</Description>
				<TypeOfTrevel>Holiday</TypeOfTrevel>
				<Destination>Мальта</Destination>
				<Hotel>Hilton</Hotel>
				<LevelOfAccommodation>5 Stars</LevelOfAccommodation>
				<NumberOfNight>7</NumberOfNight>
				<Price>445.0</Price>
			</TravelOffer>
			<TravelOffer>
				<Description>
					Исторические достопримечательности...
				</Description>
				<TypeOfTrevel>Excursion</TypeOfTrevel>
				<Destination>Прага</Destination>
				<Hotel>ResidenceBologna</Hotel>
				<LevelOfAccommodation>3 Stars</LevelOfAccommodation>
				<NumberOfNight>2</NumberOfNight>
				<Price>215.0</Price>
			</TravelOffer>
		</TravelOffers>
	</TravelAgent>
	<TravelAgent>
		<Name>Viktoria</Name>
		<Login>Viktoria</Login>
		<Pasword>asdfg</Pasword>
		<Email>Viktoria@gmail.com</Email>
		<TravelOffers>
			<TravelOffer>
				<Description>
					Тур в Италию за самыми модными и выгодными покупками...
				</Description>
				<TypeOfTrevel>ShopTour</TypeOfTrevel>
				<Destination>Милан</Destination>
				<Hotel>Ibis Milano Centro</Hotel>
				<LevelOfAccommodation>3 Stars</LevelOfAccommodation>
				<NumberOfNight>5</NumberOfNight>
				<Price>324.0</Price>
			</TravelOffer>
		</TravelOffers>
	</TravelAgent>
</TravelAgents>
